return {
    misc = {
        v_dictionary = {
            tts_welcome = [[Welcome to Balatro #1#! Using Black Hole version #2#, Steamodded version #3#. Press Y to start the game. Press 1 to read this message again. Press 2 to change the game speed. Press 3 to setup the keyboard controller. ]],
            tts_config_keybind = [[The keybind for #1# is set to #2# ... Press 6 to assign a new key. Press 5 to configure the next keybind. ]],
            tts_assign_keybind = [[Please press the key to bind to #1#. ]],
            tts_invalid_key = [[Key #1# is reserved for Black Hole configuration. Please enter a different key. ]],
            tts_confirm_continue = [[Press A to continue this run: #1#, Round #2#, Ante #3#, Money: #4#, Best Hand: #5#. ]],
            tts_game_speed = [[Changed the game speed to #1#. ]],
            tts_highlighted = [[Selected #1#]],
            tts_hand_eval = [[#1#, level #2#. #3# X #4# ]],
            tts_played_this_run = [[(played #1# #2# this run). ]],
            tts_remaining = [[- #1# #2# remaining. ]],
            tts_score_report = [[Scored #1# chips this hand, #2# total. ]],
            tts_required_score = [[#1# chips are needed to defeat the current Blind. ]],
            tts_discarded = [[Discarded #1# #2#. ]],
            tts_hook = [[Boss Blind discarded #1#]],
            tts_card_cost = [[Cost: $#1#. ]],
            tts_card_sell = [[Sell: $#1#. ]],
            tts_current_money = [[Balance: $#1#. ]],
        },
        dictionary = {
            tts_time = 'time',
            tts_times = 'times',
            tts_discard = 'discard',
            tts_discards = 'discards',
            tts_hand = 'hand',
            tts_hands = 'hands',
            tts_card = 'card',
            tts_cards = 'cards',
            tts_face_down_card = ' Face-down card',
            tts_blind_defeated = [[Blind defeated. ]],
            tts_kc_off = [[The keyboard controller is disabled. Press 4 to enable it. ]],
            tts_kc_on = [[The keyboard controller is enabled. Press 4 to disable it. Press 5 to customize keybinds. ]],
            tts_skip_blind = "Skip Blind for - ",
            tts_select_run_choice = [[Press A to start a new run. Press B to continue your run. Press Start to cancel. ]],
            tts_continuing_run = [[Continuing your run. ]],
            tts_starting_run = [[Starting your run. ]],
            tts_init_deck_select = [[Use the D-Pad Left and Right buttons to select a deck. Use the shoulder buttons to select a stake. Press A to start your run once you are ready. Press Start to cancel. ]],
            tts_locked_deck = [[This deck is locked. To play it, first fulfill its unlock condition. ]],
            tts_new_run = [[Press Y to start a new run. ]]
        },
        tts_keybinds = {
            dpleft = 'D-Pad left',
            dpright = 'D-Pad right',
            dpup = 'D-Pad up',
            dpdown = 'D-Pad down',
            x = 'Button X',
            y = 'Button Y',
            a = 'Button A',
            b = 'Button B',
            start = 'Start',
            triggerleft = 'Left Trigger',
            triggerright = 'Right Trigger',
            leftshoulder = 'Left Shoulder',
            rightshoulder = 'Right Shoulder',
            back = 'Back',
        }
    }
}