return {
    misc = {
        v_dictionary = {
            tts_welcome = [[¡Te damos la bienvenida a Balatro #1#! Usando Black Hole, versión  #2#, Steamodded #3#. Pulsa Y para empezar el juego. Pulsa 1 para leer este mensaje de nuevo. Pulsa 2 para cambiar la velocidad del juego. Pulsa 3 para configurar el controlador de teclado. ]],
            tts_config_keybind = [[La tecla asignada para #1# está asignada a #2#... Pulsa 6 para asignar una nueva tecla. Pulsa 5 para configurar la siguiente tecla. ]],
            tts_assign_keybind = [[Pulsa la tecla que quieras asignar a #1#. ]],
            tts_invalid_key = [[La tecla #1# está reservada para la configuración de Black Hole. Por favor, introduce una tecla diferente. ]],
            tts_confirm_continue = [[Pulsa A para continuar esta partida: #1#, Ronda #2#, ciega #3#, Dinero: #4#, Mejor Mano: #5#. ]],
            tts_game_speed = [[Velocidad del juego cambiada a #1#. ]],
            tts_highlighted = [[Seleccionado #1#]],
            tts_hand_eval = [[#1#, nivel #2#. #3# X #4# ]],
            tts_played_this_run = [[(jugado #1# #2# en esta partida). ]],
            tts_remaining = [[- Quedan #1# #2#. ]],
            tts_score_report = [[Has Ganado #1# fichas en esta mano, #2# en total. ]],
            tts_required_score = [[Se necesitan #1# fichas para vencer a la ciega actual. ]],
            tts_discarded = [[Descartas #1# #2#. ]],
            tts_hook = [[La ciega boss descarta #1#]],
            tts_card_cost = [[Precio: $#1#. ]],
            tts_card_sell = [[Vender: $#1#. ]],
            tts_current_money = [[Tienes: $#1#. ]],
            tts_ante = [[Apuesta #1# ]],
        },
        dictionary = {
            tts_time = 'vez',
            tts_times = 'veces',
            tts_discard = 'descartar',
            tts_discards = 'descartes',
            tts_hand = 'mano',
            tts_hands = 'manos',
            tts_card = 'carta',
            tts_cards = 'cartas',
            tts_face_down_card = ' Carta boca abajo',
            tts_blind_defeated = [[Ciega vencida. ]],
            tts_kc_off = [[El controlador de teclado está desactivado. Pulsa 4 para activarlo. ]],
            tts_kc_on = [[El controlador de teclado está activado. Pulsa 4 para desactivarlo. Pulsa 5 para personalizar las teclas. ]],
            tts_skip_blind = "Saltar ciega por - ",
            tts_tutorial = [[Pulsa X para empezar el tutorial. Pulsa A para comenzar una nueva partida. ]],
            tts_select_run_choice = [[Pulsa A para empezar una nueva partida. Pulsa B para continuar tu partida. Pulsa Start para cancelar. ]],
            tts_continuing_run = [[Continuando tu partida. ]],
            tts_starting_run = [[Empezando tu partida. ]],
            tts_init_deck_select = [[Usa los botones de la cruceta Izquierda y Derecha para seleccionar un mazo. Usa los botones superiores para seleccionar una apuesta. Pulsa A para comenzar tu partida. Pulsa Start para cancelar. Pulsa X para reiniciar el tutorial. ]],
            tts_locked_deck = [[Este mazo está bloqueado. Para jugar con él, primero cumple con su condición de desbloqueo. ]],
            tts_new_run = [[Pulsa Y para empezar una nueva partida. ]]
        },
        tts_keybinds = {
            dpleft = 'Cruceta izquierda',
            dpright = 'Cruceta derecha',
            dpup = 'Cruceta arriba',
            dpdown = 'Cruceta abajo',
            x = 'Botón X',
            y = 'Botón Y',
            a = 'Botón A',
            b = 'Botón B',
            start = 'Start',
            triggerleft = 'Gatillo Izquierdo',
            triggerright = 'Gatillo Derecho',
            leftshoulder = 'Bumper Izquierdo',
            rightshoulder = 'Bumper Derecho',
            back = 'Atrás',
        }
    }
}