[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

## Handle button hovering
[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = "self.hovering.target:hover()"
position = "after"
payload = """BlackHole.process_hover(self)"""
match_indent = true
[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = "if self.hovering.target then"
position = "before"
payload = """BlackHole.hover_time_elapsed = (BlackHole.hover_time_elapsed or 0) + dt"""
match_indent = true