[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# ease_dollars
# TODO this needs a better system - announce on cashout hover / when reading cost?
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "dollar_UI.config.object:update()"
position = "after"
payload = """tts.say(text..tostring(math.abs(mod)))
tts.say(localize{
    type = 'variable',
    key = 'tts_current_money',
    vars = { G.GAME.dollars }
})
"""
match_indent = true